spring:
  profiles:
    active: dev

  application:
    name: trip-plan-app-backend

  config:
    import: optional:file:.env

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jwt:
    secret: ${SPRING_JWT_SECRET}
    accessTokenExpiration: ${SPRING_JWT_ACCESS_TOKEN_EXPIRATION}
    refreshTokenExpiration: ${SPRING_JWT_REFRESH_TOKEN_EXPIRATION}


  social:
    naver:
      client-id: ${NAVER_CLIENT_ID}
      client-secret: ${NAVER_CLIENT_SECRET}

    google:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}

    papago:
      client-key: ${PAPAGO_CLIENT_ID}
      client-secret: ${PAPAGO_CLIENT_SECRET}

    exchange:
      auth-key: ${EXCHANGE_API_KEY:}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_USERNAME}
    password: ${GOOGLE_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
            required: true

  data:
    redis:
      host: localhost
      port: 6379

  firebase:
    service-account:
      path: ${FCM_CONFIG_PATH:config/service-account.json}

openweather:
  api:
    key: ${OPENWEATHER_API_KEY}

google:
  places:
    api-key: ${GOOGLE_PLACES_API_KEY:}
    base-url: ${GOOGLE_PLACES_BASE_URL:https://places.googleapis.com}

minio:
  endpoint: ${MINIO_ENDPOINT}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
