spring.application.name=trip-plan-app-backend

# swagger path
springdoc.swagger-ui.path=/swagger-ui.html

# api docs path
springdoc.api-docs.path=/api-docs

# package
springdoc.packages-to-scan=mars.tripplanappbackend